const queryConstants = {
    getAllReels: '/reels',
    login: '/users/sign-in',
    signup: '/users/sign-up',
    googleLogin: '/auth/google-signin',
    verifyEmail: '/users/verify-email',
    verifyOTP: '/users/verify-otp',
    forgotPassword: '/users/forgot-password',
    resetPassword: '/users/reset-password',
    getSongs: '/songs',
    uploadSong: '/songs/upload-song',
    uploadSongThumbnail: '/songs/upload-thumbnail',
    publishSong: '/songs',
    getProfile: '/users/me',
    avatarUpload: '/users/upload-avatar',
    updateUser: '/users',
    getFavoriteSongs: '/favorites?type=song',
    getAlbums: '/albums',
    getOneAlbum: '/albums/:id',
    getUserAlbum: '/albums/me',
    createAlbum: '/albums',
    fileUpload: 'songs/upload',
    songStream: '/songs/stream/:id',
    addToFavorite: '/favorites',
    songCount: '/songs/count/:id',
    userSongCount: '/songs/play',
    getAllArtists: '/users/artist',
    getPackages: '/users/packages',
    cancelSubscription: 'payments/cancel-subscription',
    addSubscription: 'payments/add-subscription',
    paymentStatus: 'payments/check-payment-status',
    updatePackage: 'payments/update-subscription',
    playHistory: '/songs/song-played-history',
    purchaseSong: '/payments/purchase-song',
    getFavoriteSongsList: '/favorites',
    getResetPassword: '/users/reset-password',
    getForgetPassword: '/users/forgot-password',
    otpVerification: "users/verify-otp",
    paymentHistory: "/users/payments",
    privateSongList: "songs/private-songs",
    addSongToPublish: "/songs/add-song-to-public",
    getSongById: "/songs/",
    editSong: "/songs/edit/",
    productsCreate: "products/create",
    allProduct: "/products",
    ownProduct: "/products/own",
    purchaseAlbum: '/payments/purchase-album',
    downloadSong: "payments/download/song",
    downloadAlbum: "payments/download/album",
    editAlbum: "/albums/edit",
    inAppDownload: "/download-album-song-in-app",
    getInAppDownload: "/songs/download-album-song-in-app",
    inAppDownLoad: "/songs/download-album-song-in-app",
    getAllCrews:"/songs/crew-details",
    addToStripeAccount:"/payments/create-stripe-account"
}
export default queryConstants
